on:
  workflow_dispatch:

jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest

    environment: 
      name: rubygems.org
      url: https://rubygems.org/gems/rapidjson

    permissions:
      contents: write
      id-token: write

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      # Release
      - uses: rubygems/release-gem@v1
